### ISSUE TITLE
Enemies have way too high drop rates

### ISSUE THREAD

**Issue by Jacie1krece** [dragon3025/Reduced-Grinding#15]
Terraria Version:
TModLoader Version: v2022.9.47.30
Reduced Grinding Version: v8.13.3

**Mods Installed**
- Reduced Grinding

**Describe the bug**
All enemies have extreme drop rates, dropping their whole loot table all at once.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a world.
2. Kill Wall of Flesh
3. Start killing hell enemies.

**Expected behaviour**
Enemies have vanilla drop rates, excluding the things that are modified by the config

**Screenshots**
Enemies drop their whole loot tables, turning this mod into something that feels just like this video: https://www.youtube.com/watch?v=wiYqZufyi3k

**Additional context**
I disabled all mods except this, though I prepared this using cheat sheet and hero's mod. Link to the video, where I show the problem: https://drive.google.com/file/d/1FpUvwh5yQ6cRFg2OZnt36120BI1f_Uqm/view?usp=share_link

**Comment by dragon3025** [comment]
I've gotten reports about this on the workshop page and in this issue: [link](https://github.com/dragon3025/Reduced-Grinding/issues/14#issue-1561825651). It's driving me crazy because I can't figure out what it is, but there has to be something going on.

I tried creating a new character using only my mod, HERO, and cheatsheet; loaded a new world; killed the wall of flesh; then started killing many enemies; and it wasn't dropping everything.

If you right click on tModLoader in steam, select properties, select betas, is the beta set to "None"?

Can you zip up your "tModLoader" folder located at "C:\Users\user_name\Documents\My Games\Terraria" and upload the zip file either here or in a file sharing site for me to use?

**Comment by Jacie1krece** [comment]
Yeah, I set my betas to either none or legacy-1.3. Also, I only prepared using these two mods, and the video is without them.

Also, I have your mod disabled in the playthrough I'm currently doing (Gun Only Expert Mode Thorium feat. Consolaria) due to this bug.

Link to the zipped tModLoader folder:
https://drive.google.com/file/d/1nrVRwaSiqfI26dQkGczFrSGxDXml7_uj/view?usp=share_link

**Comment by WildArticunoAppeared** [comment]
I'm glad I'm not the only one facing this problem. Because of this mod, the following items have become guaranteed drops for me:
- Cascade
- Hel-Fire
- Amarok
- Goodie Bag and Present (seasonal)
- Bloody Machete and Bladed Glove (Halloween)
- Biome Keys

...If only it applied to food items and nothing else...

**Comment by dragon3025** [comment]
I figured it out. The Town NPC Weapon configuration was affecting items that can be dropped by multiple enemies. For Town NPC weapons: I had a condition to test if it's a town NPC, but I didn't know I needed a condition that tested for their item because of all universally dropped items. I updated my mod and fixed the issue.
