### ISSUE TITLE
bag with bosses achiv

### ISSUE THREAD

**Issue by PermetD** [dragon3025/Reduced-Grinding#5]
Terraria Version:1.4.3.6
TModLoader Version:2022.5.103.25

**Mods Installed**
- Reduced Grinding
- jojo, cheat panel, better mage, craft accs, and many others.

**Describe the bug**
Single, start of the game, i killed 4 times skeletron, but old man respawn on a same place every time. after i start experiment and without this mode its start work. BUT! I test it now with 7.0.0.9 and its work! i create a new exp mode large world and its start to work! i dont know what happend but now its okey, thank you for this good mode!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

p.s. Sorry that i take your time, you made a greate work! thank you, man! my respect for the enthusiasm!

**Comment by PermetD** [comment]
bug was on 7.0.0.5

**Comment by dragon3025** [comment]
Thank you, I'm glad you like the mod.

This bug is so weird, I can't figure out what in my mod would cause it. Someone else in the Workshop page also had the same problem. I had an issue while testing things, with the game thinking the Celestial Pillars were around when they were gone. I wonder if it has something to do an old tModLoader version.

I'm not encountering it right now, but please let me know if it happens again.

**Comment by PermetD** [comment]
oh, man, starplatinum is me
