### ISSUE TITLE
Calamity Mod Issue with Multiple Lures

### ISSUE THREAD

**Issue by coachl4d2** [dragon3025/Reduced-Grinding#8]
Reduced grinding somehow interferes with Calamity mod's fishing rods that have multiple lures. It only fires one lure.

**Comment by dragon3025** [comment]
I tried it out every fishing rod and didn't have this problem. Is their any other mod installed besides mine and Calamity?

**Comment by coachl4d2** [comment]
I do have other mods, it seemed to solve the problem by disabling reduced grinding. I will try later with only those two mods.

**Comment by dragon3025** [comment]
A recent post on Steam lead me to look at this issue again. Maybe I was confused and thought it fires one lure when the potion is active. While testing I watched a calamity multi-lure rod fire 1 lure when the potion was inactive.

**Comment by coachl4d2** [comment]
Yes, that's what I was referring to.

**Comment by dragon3025** [comment]
I fixed the issue. It was replacing the bobber amount with a new one instead of adding to it. I also decided to split the Multi-Bobber Potion into 3 tiers. When using Calamity, the bobber amounts get adjusted and the recipes for tier 2 and 3 are pushed to be later in-game. The amount of bobbers for each tier is configurable though.
