### ISSUE TITLE
Network code ineffcient

### ISSUE THREAD

**Issue by JavidPack** [dragon3025/Reduced-Grinding#9]
You are sending a mod packet and the World Data packet every update from the server. This should be fixed, this amount of network bandwidth will surely strain servers.

Here is the effect of that, you can view this yourself by pressing F8 in-game to view the network tool

https://user-images.githubusercontent.com/4522492/183008560-f2df7f1b-a5d6-4b57-ab10-b40202273abf.mp4

**Comment by dragon3025** [comment]
Thank you, that sounds very bad. I set it to only update when any of the variables get changed, instead of every update, so I think I fixed it, but I'm not sure. To test it, I right clicked on of my tiles, ([MoonBall.cs](https://github.com/dragon3025/Reduced-Grinding/blob/3f9fece23e6c96486dffbce9322dd34d3cab700a/Tiles/MoonBall.cs#L48)), and it sends from the client to the server just like in the update file. I noticed when I do this the received and sent numbers go up and they never go down and it turns from green to red; I don't know if that's bad.

**Comment by JavidPack** [comment]
Seems fixed to me, I can confirm that it is not sending the packet every update. This also fixed a Boss Checklist scrolling issue that I was trying to deal with. The color is fine, the world packet is really large so it'll show up as red most the time.
